const languages = [
  { no: "0", name: "Auto", native: "Detect", code: "auto" },
  { no: "1", name: "Afrikaans", native: "Afrikaans", code: "af" },
  { no: "2", name: "Albanian", native: "Shqip", code: "sq" },
  { no: "3", name: "Arabic", native: "عربي", code: "ar" },
  { no: "4", name: "Armenian", native: "Հայերէն", code: "hy" },
  { no: "5", name: "Assamese", native: "অসমীয়া", code: "as" },
  { no: "6", name: "Azerbaijani", native: "آذربایجان دیلی", code: "az" },
  { no: "7", name: "Basque", native: "Euskara", code: "eu" },
  { no: "8", name: "Belarusian", native: "Беларуская", code: "be" },
  { no: "9", name: "Bengali", native: "বাংলা", code: "bn" },
  { no: "10", name: "Bulgarian", native: "Български", code: "bg" },
  { no: "11", name: "Catalan", native: "Català", code: "ca" },
  { no: "12", name: "Chinese (Simplified)", native: "中文简体", code: "zh-CN" },
  { no: "13", name: "Chinese (Traditional)", native: "中文繁體", code: "zh-TW" },
  { no: "14", name: "Croatian", native: "Hrvatski", code: "hr" },
  { no: "15", name: "Czech", native: "Čeština", code: "cs" },
  { no: "16", name: "Danish", native: "Dansk", code: "da" },
  { no: "17", name: "Dutch", native: "Nederlands", code: "nl" },
  { no: "18", name: "English", native: "English", code: "en" },
  { no: "19", name: "Estonian", native: "Eesti keel", code: "et" },
  { no: "20", name: "Filipino", native: "Filipino", code: "tl" },
  { no: "21", name: "Finnish", native: "Suomi", code: "fi" },
  { no: "22", name: "French", native: "Français", code: "fr" },
  { no: "23", name: "Galician", native: "Galego", code: "gl" },
  { no: "24", name: "Georgian", native: "ქართული", code: "ka" },
  { no: "25", name: "German", native: "Deutsch", code: "de" },
  { no: "26", name: "Greek", native: "Ελληνικά", code: "el" },
  { no: "27", name: "Gujarati", native: "ગુજરાતી", code: "gu" },
  { no: "28", name: "Haitian Creole", native: "Kreyòl ayisyen", code: "ht" },
  { no: "29", name: "Hebrew", native: "עברית", code: "iw" },
  { no: "30", name: "Hindi", native: "हिन्दी", code: "hi" },
  { no: "31", name: "Hungarian", native: "Magyar", code: "hu" },
  { no: "32", name: "Icelandic", native: "Íslenska", code: "is" },
  { no: "33", name: "Indonesian", native: "Bahasa Indonesia", code: "id" },
  { no: "34", name: "Irish", native: "Gaeilge", code: "ga" },
  { no: "35", name: "Italian", native: "Italiano", code: "it" },
  { no: "36", name: "Japanese", native: "日本語", code: "ja" },
  { no: "37", name: "Kannada", native: "ಕನ್ನಡ", code: "kn" },
  { no: "38", name: "Korean", native: "한국어", code: "ko" },
  { no: "39", name: "Latvian", native: "Latviešu", code: "lv" },
  { no: "40", name: "Lithuanian", native: "Lietuvių kalba", code: "lt" },
  { no: "41", name: "Macedonian", native: "Македонски", code: "mk" },
  { no: "42", name: "Malay", native: "Malay", code: "ms" },
  { no: "43", name: "Malayalam", native: "മലയാളം", code: "ml" },
  { no: "44", name: "Maltese", native: "Malti", code: "mt" },
  { no: "45", name: "Marathi", native: "मराठी", code: "mr" },
  { no: "46", name: "Nepali", native: "नेपाली", code: "ne" },
  { no: "47", name: "Norwegian", native: "Norsk", code: "no" },
  { no: "48", name: "Odia (Oriya)", native: "ଓଡ଼ିଆ", code: "or" },
  { no: "49", name: "Persian", native: "فارسی", code: "fa" },
  { no: "50", name: "Polish", native: "Polski", code: "pl" },
  { no: "51", name: "Portuguese", native: "Português", code: "pt" },
  { no: "52", name: "Punjabi", native: "ਪੰਜਾਬੀ", code: "pa" },
  { no: "53", name: "Romanian", native: "Română", code: "ro" },
  { no: "54", name: "Russian", native: "Русский", code: "ru" },
  { no: "55", name: "Sanskrit", native: "संस्कृतम्", code: "sa" },
  { no: "56", name: "Serbian", native: "Српски", code: "sr" },
  { no: "57", name: "Slovak", native: "Slovenčina", code: "sk" },
  { no: "58", name: "Slovenian", native: "Slovensko", code: "sl" },
  { no: "59", name: "Spanish", native: "Español", code: "es" },
  { no: "60", name: "Swahili", native: "Kiswahili", code: "sw" },
  { no: "61", name: "Swedish", native: "Svenska", code: "sv" },
  { no: "62", name: "Tamil", native: "தமிழ்", code: "ta" },
  { no: "63", name: "Telugu", native: "తెలుగు", code: "te" },
  { no: "64", name: "Thai", native: "ไทย", code: "th" },
  { no: "65", name: "Turkish", native: "Türkçe", code: "tr" },
  { no: "66", name: "Ukrainian", native: "Українська", code: "uk" },
  { no: "67", name: "Urdu", native: "اردو", code: "ur" },
  { no: "68", name: "Vietnamese", native: "Tiếng Việt", code: "vi" },
  { no: "69", name: "Welsh", native: "Cymraeg", code: "cy" },
  { no: "70", name: "Yiddish", native: "ייִדיש", code: "yi" },
];
